export const SET_PAGE = 'product@set_page'
export const PAGE_REQUEST_START = 'product@page_request_start'
export const PAGE_REQUEST_END = 'product@page_request_end'
export const SET_CATEGORIES = 'product@set_categories'
export const SET_ALL_ATTRS = 'product@set_all_attrs'