import { createApp } from 'vue'
// import App from './App01-setup.vue'
// import App from './App02-reactive.vue'
// import App from './App03-ref.vue'
// import App from './App04-shallowReactive.vue'
// import App from './App05-shallowRef.vue'
// import App from './App06-toRaw.vue'
// import App from './App07-toRef.vue'
// import App from './App08-toRefs.vue'
// import App from './App09-customRef.vue'
// import App from './App10-computed.vue'
// import App from './App11-watch.vue'
// import App from './App12-life.vue'
// import App from './App13-dom.vue'
// import App from './App14-father.vue'
// import App from './App15-father.vue'
// import App from './App16-father.vue'
import App from './App17-proxy.vue'

createApp(App).mount('#app')
