export const SET_PAGE = 'user@set_page'
export const PAGE_REQUEST_START = 'user@page_request_start'
export const PAGE_REQUEST_END = 'user@page_request_end'
export const SET_ICON = 'user@set_icon'
export const SET_ICON_ERROR = 'user@set_icon_error'