export const SET_PAGE = 'category@set_page'
export const PAGE_REQUEST_START = 'category@page_request_start'
export const PAGE_REQUEST_END = 'category@page_request_end'
export const SET_ICON = 'category@set_icon'
export const SET_ICON_ERROR = 'category@set_icon_error'
export const SET_CATEGORIES = 'category@set_categories'